"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Highway;
(function (Highway) {
    Highway["BridleWay"] = "https://w3id.org/openstreetmap/terms#BridleWay";
    Highway["Crossing"] = "https://w3id.org/openstreetmap/terms#Crossing";
    Highway["Cycleway"] = "https://w3id.org/openstreetmap/terms#CycleHighway";
    Highway["Footway"] = "https://w3id.org/openstreetmap/terms#FootHighway";
    Highway["Giveway"] = "https://w3id.org/openstreetmap/terms#Giveway";
    Highway["LivingStreet"] = "https://w3id.org/openstreetmap/terms#LivingStreet";
    Highway["Motorway"] = "https://w3id.org/openstreetmap/terms#Motorway";
    Highway["MotorwayLink"] = "https://w3id.org/openstreetmap/terms#MotorwayLink";
    Highway["Path"] = "https://w3id.org/openstreetmap/terms#Path";
    Highway["Primary"] = "https://w3id.org/openstreetmap/terms#Primary";
    Highway["PrimaryLink"] = "https://w3id.org/openstreetmap/terms#PrimaryLink";
    Highway["Proposed"] = "https://w3id.org/openstreetmap/terms#Proposed";
    Highway["Residential"] = "https://w3id.org/openstreetmap/terms#Residential";
    Highway["Road"] = "https://w3id.org/openstreetmap/terms#Road";
    Highway["Secondary"] = "https://w3id.org/openstreetmap/terms#Secondary";
    Highway["SecondaryLink"] = "https://w3id.org/openstreetmap/terms#SecondaryLink";
    Highway["Service"] = "https://w3id.org/openstreetmap/terms#Service";
    Highway["Steps"] = "https://w3id.org/openstreetmap/terms#Steps";
    Highway["Stop"] = "https://w3id.org/openstreetmap/terms#Stop";
    Highway["Tertiary"] = "https://w3id.org/openstreetmap/terms#Tertiary";
    Highway["TertiaryLink"] = "https://w3id.org/openstreetmap/terms#TertiaryLink";
    Highway["Track"] = "https://w3id.org/openstreetmap/terms#Track";
    Highway["TrafficSignals"] = "https://w3id.org/openstreetmap/terms#TrafficSignals";
    Highway["Trunk"] = "https://w3id.org/openstreetmap/terms#Trunk";
    Highway["TrunkLink"] = "https://w3id.org/openstreetmap/terms#TrunkLink";
    Highway["Unclassified"] = "https://w3id.org/openstreetmap/terms#Unclassified";
})(Highway || (Highway = {}));
exports.default = Highway;
//# sourceMappingURL=Highway.js.map